"""empty message

Revision ID: 8c646c70d3b3
Revises: 
Create Date: 2021-03-30 14:44:16.411426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c646c70d3b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('q1', sa.Float(), nullable=False),
    sa.Column('q2', sa.Float(), nullable=False),
    sa.Column('q3', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sex', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('real', sa.Integer(), nullable=False),
    sa.Column('roman', sa.Integer(), nullable=False),
    sa.Column('human', sa.Integer(), nullable=False),
    sa.Column('ideal', sa.Integer(), nullable=False),
    sa.Column('agent', sa.Integer(), nullable=False),
    sa.Column('relation', sa.Integer(), nullable=False),
    sa.Column('trust', sa.Integer(), nullable=False),
    sa.Column('manual', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('culture', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trainer',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sex', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('real', sa.Integer(), nullable=False),
    sa.Column('roman', sa.Integer(), nullable=False),
    sa.Column('human', sa.Integer(), nullable=False),
    sa.Column('ideal', sa.Integer(), nullable=False),
    sa.Column('agent', sa.Integer(), nullable=False),
    sa.Column('relation', sa.Integer(), nullable=False),
    sa.Column('trust', sa.Integer(), nullable=False),
    sa.Column('manual', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('culture', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('sale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_sale', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('trainer_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['trainer_name'], ['trainer.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sale')
    op.drop_table('trainer')
    op.drop_table('member')
    op.drop_table('machine')
    # ### end Alembic commands ###
